theme: jekyll-theme-midnight
# Site Settings
locale                   : "en-US"
title                    : "Melody Asghari's (slightly less annoying) landing page"
title_separator          : "-"
name                     : &name "Melody Asghari"
description              : &description "Computer Engineering Student"
url                      : https://melasg.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "melasg/melasg.github.io"


